server:
  port: 8081
spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
#  sql:
#    init:
#      mode: embedded
  liquibase:
    enabled: true
    change-log: changelog.xml
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB